name: Amy Mann
favicon: null
layout_spectrum: 0.5328263188712299
typography_spectrum: 0.34911
title: Amy Mann
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fef7e7'
    - '#341b2e'
    - '#7fa1a2'
    - '#b1d2c1'
    - '#786952'
  brandStrength: 0.9358828621916473
  lightness: 0.4630957862827927
  saturation: 0.28605416254140437
  rhythmicContrast: 0.9610611172392964
purpose: []
